
#define SCREEN_LENGHT 800
#define SCREEN_HEIGHT 600

#define PLAYER_SIZE 64

#define GAME_TITLE "Mental War v0.1"

#define FRAMERATE 60

#define MAX_FORCE 100

#define MIN_FORCE 0

#define LFOCUS_METER_POS_X SCREEN_LENGHT*0.02
#define RFOCUS_METER_POS_X SCREEN_LENGHT*0.94
#define FOCUS_METER_POS_Y SCREEN_HEIGHT*0.30
